// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD0PZ0CZ869BJnwUMH89r8L7MMScDIJkw',
    appId: '1:751288042998:web:c6cd9657c6460a3a1eb3d7',
    messagingSenderId: '751288042998',
    projectId: 'dronaid-325c8',
    authDomain: 'dronaid-325c8.firebaseapp.com',
    storageBucket: 'dronaid-325c8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBteaiHoFpwWoV1SWj0bCxJVQhJPU_27sA',
    appId: '1:751288042998:android:235169293b89f7cf1eb3d7',
    messagingSenderId: '751288042998',
    projectId: 'dronaid-325c8',
    storageBucket: 'dronaid-325c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfzsfo66OcuuEfrOuqSuXsK3SdbziKP1Q',
    appId: '1:751288042998:ios:7b22463617fa99ff1eb3d7',
    messagingSenderId: '751288042998',
    projectId: 'dronaid-325c8',
    storageBucket: 'dronaid-325c8.firebasestorage.app',
    iosBundleId: 'com.example.liveLoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfzsfo66OcuuEfrOuqSuXsK3SdbziKP1Q',
    appId: '1:751288042998:ios:7b22463617fa99ff1eb3d7',
    messagingSenderId: '751288042998',
    projectId: 'dronaid-325c8',
    storageBucket: 'dronaid-325c8.firebasestorage.app',
    iosBundleId: 'com.example.liveLoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD0PZ0CZ869BJnwUMH89r8L7MMScDIJkw',
    appId: '1:751288042998:web:dc27094c5709af1c1eb3d7',
    messagingSenderId: '751288042998',
    projectId: 'dronaid-325c8',
    authDomain: 'dronaid-325c8.firebaseapp.com',
    storageBucket: 'dronaid-325c8.firebasestorage.app',
  );
}
