// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV1IAIfb7EtLVKxP4t3xEY1CCcJHOvGPo',
    appId: '1:171193895763:web:abb7329ccd811a398a2fa6',
    messagingSenderId: '171193895763',
    projectId: 'uas2026-b3b43',
    authDomain: 'uas2026-b3b43.firebaseapp.com',
    databaseURL: 'https://uas2026-b3b43-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'uas2026-b3b43.firebasestorage.app',
    measurementId: 'G-ZY44E3NFXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2M2QQ1eUfTIzh6d0RWAy3sLisJjpL_Y4',
    appId: '1:171193895763:android:6ddf4053d5943ca78a2fa6',
    messagingSenderId: '171193895763',
    projectId: 'uas2026-b3b43',
    databaseURL: 'https://uas2026-b3b43-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'uas2026-b3b43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqlGYOh2ZOBkoB034XgPKzgn4-d4nrMsY',
    appId: '1:171193895763:ios:6989d4cac8129a508a2fa6',
    messagingSenderId: '171193895763',
    projectId: 'uas2026-b3b43',
    databaseURL: 'https://uas2026-b3b43-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'uas2026-b3b43.firebasestorage.app',
    iosBundleId: 'com.example.liveLoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqlGYOh2ZOBkoB034XgPKzgn4-d4nrMsY',
    appId: '1:171193895763:ios:6989d4cac8129a508a2fa6',
    messagingSenderId: '171193895763',
    projectId: 'uas2026-b3b43',
    databaseURL: 'https://uas2026-b3b43-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'uas2026-b3b43.firebasestorage.app',
    iosBundleId: 'com.example.liveLoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV1IAIfb7EtLVKxP4t3xEY1CCcJHOvGPo',
    appId: '1:171193895763:web:c42f30d06966c1c98a2fa6',
    messagingSenderId: '171193895763',
    projectId: 'uas2026-b3b43',
    authDomain: 'uas2026-b3b43.firebaseapp.com',
    databaseURL: 'https://uas2026-b3b43-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'uas2026-b3b43.firebasestorage.app',
    measurementId: 'G-MTY744XZD7',
  );

}