// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDNoPCZwIILItxyQWedyuQwJobEEHEieY',
    appId: '1:23640679370:web:944d8f2b30b411501fe533',
    messagingSenderId: '23640679370',
    projectId: 'test-mavlink',
    authDomain: 'test-mavlink.firebaseapp.com',
    databaseURL: 'https://test-mavlink-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-mavlink.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYbMPLL9UkjluNjKgtOM4aV7UTHlz4zbQ',
    appId: '1:23640679370:android:27c5f6c25200d6d81fe533',
    messagingSenderId: '23640679370',
    projectId: 'test-mavlink',
    databaseURL: 'https://test-mavlink-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-mavlink.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXBW1BXdJ5E5l_8uYWJGdCaxD8xGjaEDk',
    appId: '1:23640679370:ios:adcaf7f3cfbca0be1fe533',
    messagingSenderId: '23640679370',
    projectId: 'test-mavlink',
    databaseURL: 'https://test-mavlink-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-mavlink.firebasestorage.app',
    iosBundleId: 'com.example.liveLoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXBW1BXdJ5E5l_8uYWJGdCaxD8xGjaEDk',
    appId: '1:23640679370:ios:adcaf7f3cfbca0be1fe533',
    messagingSenderId: '23640679370',
    projectId: 'test-mavlink',
    databaseURL: 'https://test-mavlink-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-mavlink.firebasestorage.app',
    iosBundleId: 'com.example.liveLoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDNoPCZwIILItxyQWedyuQwJobEEHEieY',
    appId: '1:23640679370:web:8c8adee928fb47aa1fe533',
    messagingSenderId: '23640679370',
    projectId: 'test-mavlink',
    authDomain: 'test-mavlink.firebaseapp.com',
    databaseURL: 'https://test-mavlink-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-mavlink.firebasestorage.app',
  );

}